global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'knative-serving'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - knative-serving
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: activator|controller|webhook|autoscaler

  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      # Скрейпим только pod'ы с prometheus.io/scrape=true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true

      # Берём path из prometheus.io/path (если есть)
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)

      # Берём port из prometheus.io/port (если есть) и подставляем в __address__
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
